// <auto-generated />
using System;
using ICT2106Payment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICT2106Payment.Migrations
{
    [DbContext(typeof(WalletContext))]
    [Migration("20200216090727_WalletCreate")]
    partial class WalletCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_2106PaymentModule.Models.Wallet", b =>
                {
                    b.Property<string>("walletId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("userId");

                    b.Property<decimal>("walletAmount");

                    b.HasKey("walletId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("_2106PaymentModule.Models.WalletTransaction", b =>
                {
                    b.Property<string>("walletTransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("transactionAmount");

                    b.Property<DateTime>("transactionDate");

                    b.Property<string>("transactionType");

                    b.Property<string>("walletId");

                    b.HasKey("walletTransactionId");

                    b.ToTable("WalletTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
